- backend/src/controllers/auth-logs.controller.ts
- backend/src/dtos/auth-logs.dto.ts
- backend/src/entities/auth-logs.entity.ts
- backend/src/routes.ts
- backend/src/services/auth-logs.service.ts
- Closes #37 
- This PR introduces the auth-logs module, which manages authentication logs.
- Created auth-logs.controller.ts to handle HTTP requests
- Defined auth-logs.dto.ts with the required DTOs
- Created auth-logs.entity.ts with the base structure
- Implemented auth-logs.service.ts with the business logic 
- Modified routes.ts to include the auth-logs module routes
Video:
https://www.loom.com/share/0c618f0744e04854bfbb464b75aa494f?sid=1bd115d4-a280-464d-8d39-c1d3c9a50c02
> feat: auth logs

- backend/src/app.module.ts
- backend/src/controllers/ratings.controller.ts
- backend/src/dtos/ratings.dto.ts
- backend/src/entities/ratings.entity.ts
- backend/src/main.ts
- backend/src/ratings.module.ts
- backend/src/services/ratings.service.ts
- Implement ratings entity
- Complete ratings entity with TypeORM decorators and relationships
- DTOs for creating, updating, and returning ratings
- Service layer with CRUD operations
- Controller with protected endpoints
- Proper module setup for dependency injection
- Main application setup with validation
-
> Implement ratings entity

- backend/src/controllers/certifications.controller.ts
- backend/src/dtos/certifications.dto.ts
- backend/src/entities/certifications.entity.ts
- backend/src/routes.ts
- backend/src/services/certifications.service.ts
- Closes #34
- Implementation of the certifications module in the backend architecture.
- [✔️] `certifications.entity.ts` created in `@/entities/` with the base structure.
- [✔️] `certifications.dto.ts` created in `@/dtos/` with the required DTOs.
- [✔️] `certifications.service.ts` created in `@/services/` with business logic.
- [✔️] `certifications.controller.ts` created in `@/controllers/` to handle HTTP requests.
- [✔️] `routes.ts` updated with the necessary routes for `certifications`.
- https://www.loom.com/share/969c20189c34428aacfb304ecd92945f?sid=ff970304-e966-48b7-a376-7d62d43d2b15
> feat: add certifications entity

- backend/src/controllers/conversations.controller.ts
- backend/src/dtos/conversations.dto.ts
- backend/src/entities/conversations.entity.ts
- backend/src/repositories/conversations.repository.ts
- backend/src/routes.ts
- backend/src/services/conversations.service.ts
- package.json
- pnpm-lock.yaml
- Closes #35  : 
This PR lays the foundation for managing conversations, including the entity, repository, service, controller, and routes.
- conversations.entity.ts is created in @/entities/ with the base structure for the Conversation entity.
- conversations.dto.ts is created in @/dtos/ with the necessary DTOs for the Conversation model.
**Note: The conversationId, createdAt, and updatedAt fields are not included in the DTO because they are automatically handled by the database.**
- conversations.repository.ts is created in @/repositories/ to manage database queries related to conversations.
- conversations.service.ts is created in @/services/ to implement the business logic for managing conversations.
- conversations.controller.ts is created in @/controllers/ to handle incoming HTTP …
> Feat/implement conversations entity 

- backend/src/app.module.ts
- backend/src/controllers/user-achievements.controller.ts
- backend/src/dtos/user-achievements.dto.ts
- backend/src/entities/user-achievements.entity.ts
- backend/src/repositories/user-achievements.repository.ts
- backend/src/routes.ts
- backend/src/services/user-achievements.service.ts
- backend/src/user-achievements.module.ts
feat:Implement-user-achievements-entity
- Closes #38 
This PR implements the user-achievements entity in the backend, following the defined folder and file structure. It includes the necessary DTOs, service, repository, entity, and controller to handle user achievements.
Created user-achievements.entity.ts in @/entities/ to define the database schema for user achievements.
Created user-achievements.dto.ts in @/dtos/ to define DTOs for handling user achievement data.
Created user-achievements.repository.ts in @/repositories/ to manage database queries.
Created user-achievements.service.ts in @/services/ to implement business logic.
Created user-achievements.controller.ts in @/controllers/ to handle HTTP requests.
Updated routes.ts to register user-achievements routes.
** TESTS** 
Create …
> feat:Implement-user-achievements-entity

- backend/src/app.module.ts
- backend/src/controllers/conversations.controller.ts
- backend/src/controllers/users.controller.ts
- backend/src/dtos/users.dto.ts
- backend/src/entities/activity-logs.entity.ts
- backend/src/entities/users.entity.ts
- backend/src/modules/users.module.ts
- backend/src/repositories/users.repository.ts
- backend/src/routes.ts
- backend/src/services/users.service.ts
- Closes #43 
- Added Users entity with complete implementation including entity definition, DTOs, repository, service, and controller following NestJS patterns. Implemented all required fields from the database schema with proper validation and error handling. The implementation provides a complete RESTful API for user management with CRUD operations.
- Created users.entity.ts with all required database fields (user_id, wallet_address, email, username, created_at, last_login, is_active, two_factor_enabled)
- Implemented users.dto.ts with CreateUserDto, UpdateUserDto, and UserResponseDto
- Implemented users.repository.ts following NestJS patterns with proper dependency injection
- Implemented users.service.ts with business logic for CRUD operations and validation
- Implemented …
> [FEAT] Add users entity

- backend/src/controllers/project.controller.ts
- backend/src/dtos/project.dto.ts
- backend/src/entities/project.entity.ts
- backend/src/repositories/portfolio-items.repository.ts
- backend/src/services/achievements.service.ts
- backend/src/services/project.service.ts
- Closes #42 
- Implemented the `ProjectService` following the structure of `RatingsService`.
- Created `ProjectController` with full CRUD operations.
- Added `ProjectService` using `@Injectable()` and `@InjectRepository()`.
- Implemented `create`, `findAll`, `findOne`, `update`, and `remove` methods.
- Created `ProjectController` with `@Post`, `@Get`, `@Put`, and `@Delete` routes.
> feat: adding project system

- package-lock.json
- src/app/profile/page.tsx
- src/components/profile/edit-profile-button.tsx
- src/components/profile/profile-details.tsx
- src/components/profile/profile-header.tsx
- src/components/profile/profile-layout.tsx
- src/components/profile/profile-sidebar.tsx
- src/components/profile/profile-stats.tsx
- src/components/profile/sign-out-button.tsx
- src/layouts/Header.tsx
- Closes #93
This PR implements a responsive user profile interface using Tailwind CSS. The implementation follows the design mockup exactly and provides a clean, modern user experience for viewing and managing profile information.
- Created modular components for different sections of the profile page
- Implemented responsive layout that works on mobile and desktop
- Used Tailwind CSS for styling without external component libraries
- Added profile header with avatar and user information
- Implemented sidebar navigation with active state indicators
- Created form fields for personal information display
- Added skills tags with appropriate styling
- Implemented statistics cards for user metrics
- Added action buttons (Edit Profile, Sign Out) with proper styling
> feat: redesing my profile page

- backend/docker-compose.yml
- backend/package-lock.json
- backend/package.json
- backend/src/app.module.ts
- backend/src/modules/invoices/controller.ts
- backend/src/modules/invoices/module.ts
- backend/src/modules/invoices/service.ts
- backend/src/modules/pdf/module.ts
- backend/src/modules/pdf/service.ts
- backend/src/modules/storage/module.ts
- backend/src/modules/storage/service.ts
- backend/src/modules/transactions/entity.ts
- backend/src/modules/transactions/module.ts
- backend/src/modules/transactions/service.ts
- Closes #81 
- This implementation adds PDF invoice generation capabilities to the OFFER-HUB platform. The system automatically creates PDF invoices when transactions are completed and stores them in MinIO, a cloud-native storage solution.
1. Transaction Completion:
- When a transaction status is updated to "completed" (either during creation or update)
- The system checks if the transaction is of type "payment" or "escrow_release"
2. Invoice Generation:
- InvoiceService converts transaction data into invoice format
- PdfService creates a PDF document with all transaction details
- The PDF is temporarily saved to disk
3. Cloud Storage:
- The PDF is uploaded to MinIO storage
- Only the relative path is stored in the database (not the full URL)
- The temporary file is deleted
4. Access and …
> [FEAT] Create an Invoice and Payment Receipt System in PDF

- package-lock.json
- package.json
- src/app/post-project/loading.tsx
- src/app/post-project/page.tsx
- src/components/payments/invoice-generator.tsx
- src/components/payments/payment-chart.tsx
- src/components/payments/payment-history.tsx
- src/components/payments/payment-methods.tsx
- src/components/payments/payment-overview.tsx
- src/components/payments/payment-tabs.tsx
- src/components/payments/pending-payments.tsx
- src/components/payments/recent-transactions-table.tsx
- src/components/payments/tax-documents.tsx
- src/components/post-project/project-attachments.tsx
- src/components/post-project/project-basic-info.tsx
- src/components/post-project/project-budget.tsx
- src/components/post-project/project-requirements.tsx
- src/components/post-project/project-review.tsx
- src/components/post-project/project-steps.tsx
- src/components/post-project/project-success.tsx
- src/components/ui/radio-group.tsx
**Create post-project flow with dynamic step components and reusable UI elements**
- Closes #issue-ID
This PR introduces the entire project posting flow under `/post-project`. It includes modular components for each step of the flow (basic info, requirements, budget, etc.) and integrates reusable UI elements. Also adjusts existing payment components to use the new shared UI library.
- Created route and loading page for `/post-project`.
- Added step-by-step components: `project-steps`, `project-basic-info`, `project-requirements`, `project-budget`, `project-attachments`, `project-review`, `project-success`.
- Introduced new reusable component: `RadioGroup`.
- Updated multiple payment components to properly use shared UI elements (`Alert`, `Dialog`, `Card`, `Select`, etc.).
- Updated …
> Feat: create project page

- backend/middleware/auth.middleware.ts
- backend/src/database/migrations/xxxx-create-disputes.ts
- backend/src/modules/admin/controller.ts
- backend/src/modules/auth/auth.service.ts
- backend/src/modules/auth/roles.guard.ts
- Closes #82
This PR introduces a robust Role-Based Access Control (RBAC) framework to enforce granular permissions across the application. By formalizing access policies around three core roles (admin, freelancer, client), we establish a secure foundation for authorization that integrates seamlessly with our existing authentication stack.
- Created dedicated `roles` table with constrained `name` uniqueness  
- Established referential integrity via `role_id` foreign key in `users` table  
- Implemented default role assignment (`freelancer`) at schema level  
- Introduced `RolesGuard` leveraging NestJS's metadata reflection  
- Designed guard to fail closed (explicit allow-list of required roles)  
- Maintained extensibility through decorator-based role declarations  
- Enhanced JWT …
> Feat: Role-Based Access Control (RBAC) System Implementation

- src/components/freelancer-profile/steps/index.tsx
- src/components/freelancer-profile/steps/user-choose-role.tsx
- Closes #125
- Implement responsive and styled UserChooseRole step for freelancer profile flow and added to `steps/index`
- Created src/components/freelancer-profile/steps/user-choose-role.tsx with all required UI and logic.
- Registered the component in the step flow.
- Ensured all content is centered and responsive.
- Used Tailwind config colors for all UI elements.
- Added a border around the card.
- Added TODO comments for next-step logic, persistence, and accessibility.
[Loom](https://www.loom.com/share/6626954499944af69fd379bafe5ca68b?sid=b05e5464-ceff-45de-af0f-785b57a80411)
> feat: user choose role

- src/hooks/useUpdateEscrow.ts
- Closes #174 
The implementation matches the example repository's patterns and integrates with the Trustless Work escrow package. It handles asynchronous operations properly and provides appropriate error handling and state management.
-
-
> Feat: implement `useUpdateEscrow` hook

- src/app/user-management/verification/page.tsx
- src/components/Header.tsx
- src/components/profile/change-password-form.tsx
- src/components/profile/edit-profile-form.tsx
- src/components/profile/profile-card.tsx
- src/components/profile/profile-section.tsx
feat: Implement Profile Feature in Verification Page
- Closes #203 
Implemented a comprehensive profile management system integrated directly into the user verification page. This feature provides users with a centralized location to manage their profile information and security settings through a clean, modern interface that matches the Figma design specifications.
The profile feature includes a main overview card, edit profile form with validation, and a password reset form with real-time strength indicators. All components are modular and reusable, with proper navigation flow and URL synchronization.
- ✨ Added Profile tab to verification page with seamless integration
- 🏗️ Created modular profile components (ProfileCard, EditProfileForm, ChangePasswordForm, ProfileSection)
- 🎨 …
> feat: Implement Profile Feature in Verification Page

- src/app/(client)/onboarding/sign-in/not-found/page.tsx
- src/components/auth/NotFoundBanner.tsx
- src/components/auth/RoleSelector.tsx
- src/components/auth/SignInForm.tsx
Feature: Account not found 
- Closes #207 
- This PR implements the SignInNotFound Page with the components RoleSelector, NotFoundBanner, and the SignInForm
-Creates the components requested: RoleSelector, NotFoundComponent, SignInForm and the SignInNotFoundPage
> feat:Account not Found

- contracts-offerhub/Cargo.lock
- contracts-offerhub/contracts/job-posting /Cargo.toml
- contracts-offerhub/contracts/job-posting /Makefile
- contracts-offerhub/contracts/job-posting /src/error.rs
- contracts-offerhub/contracts/job-posting /src/events.rs
- contracts-offerhub/contracts/job-posting /src/lib.rs
- contracts-offerhub/contracts/job-posting /src/test.rs
- contracts-offerhub/contracts/job-posting /src/types.rs
- contracts-offerhub/contracts/job-posting /test_snapshots/test/test_close_job_already_closed.1.json
- contracts-offerhub/contracts/job-posting /test_snapshots/test/test_close_job_success.1.json
- contracts-offerhub/contracts/job-posting /test_snapshots/test/test_close_job_unauthorized.1.json
- contracts-offerhub/contracts/job-posting /test_snapshots/test/test_get_job_not_found.1.json
- contracts-offerhub/contracts/job-posting /test_snapshots/test/test_post_and_get_job_success.1.json
- contracts-offerhub/contracts/job-posting /test_snapshots/test/test_post_job_invalid_input.1.json
- contracts-offerhub/contracts/nft-contract/src/access.rs
- contracts-offerhub/contracts/nft-contract/src/events.rs
- contracts-offerhub/contracts/nft-contract/src/lib.rs
- contracts-offerhub/contracts/nft-contract/src/metadata.rs
- contracts-offerhub/contracts/nft-contract/src/nft.rs
- contracts-offerhub/contracts/nft-contract/src/storage.rs
- contracts-offerhub/contracts/nft-contract/src/test.rs
- contracts-offerhub/contracts/nft-contract/src/types.rs
- contracts-offerhub/contracts/toker-reward-contract/src/events.rs
- contracts-offerhub/contracts/toker-reward-contract/src/lib.rs
- contracts-offerhub/contracts/toker-reward-contract/src/reward.rs
- contracts-offerhub/contracts/toker-reward-contract/src/storage.rs
- contracts-offerhub/contracts/toker-reward-contract/src/test.rs
- contracts-offerhub/contracts/toker-reward-contract/src/types.rs
Implement JobPostingContract for Creating and Managing On-Chain Job Offers
- Closes #194
This PR introduces a Soroban smart contract in `Contracts-OfferHub/src/job-posting` that allows clients to create and manage job offers directly on-chain, tied to their wallet addresses. This contract serves as the foundation for connecting job listings with proposals from freelancers within the OfferHub platform.
🔧 Implemented Functions:
* `post_job(owner:Address ,title: String, description: String, budget: u64) -> u32`
* Creates a new job post with metadata: owner address, title, description, budget, and timestamp
* `get_job(job_id: u32) -> JobData`
* Retrieves job details; returns an error if the job ID is not found
* `close_job(job_id: u32)`
* Closes a job; only the original job creator (owner) …
> Job posting contract

- contracts-offerhub/Cargo.lock
- contracts-offerhub/contracts/proposal/Cargo.toml
- contracts-offerhub/contracts/proposal/Makefile
- contracts-offerhub/contracts/proposal/src/error.rs
- contracts-offerhub/contracts/proposal/src/events.rs
- contracts-offerhub/contracts/proposal/src/lib.rs
- contracts-offerhub/contracts/proposal/src/test.rs
- contracts-offerhub/contracts/proposal/src/types.rs
- contracts-offerhub/contracts/proposal/test_snapshots/test/test_get_individual_proposal.1.json
- contracts-offerhub/contracts/proposal/test_snapshots/test/test_get_proposals_for_job.1.json
- contracts-offerhub/contracts/proposal/test_snapshots/test/test_get_proposals_for_nonexistent_job.1.json
- contracts-offerhub/contracts/proposal/test_snapshots/test/test_initialize_already_initialized.1.json
- contracts-offerhub/contracts/proposal/test_snapshots/test/test_initialize_contract.1.json
- contracts-offerhub/contracts/proposal/test_snapshots/test/test_remove_proposal.1.json
- contracts-offerhub/contracts/proposal/test_snapshots/test/test_submit_duplicate_proposal.1.json
- contracts-offerhub/contracts/proposal/test_snapshots/test/test_submit_proposal_invalid_input.1.json
- contracts-offerhub/contracts/proposal/test_snapshots/test/test_submit_proposal_success.1.json
Added `ProposalContract`  for freelancer job proposal submissions
- Closes #195 
- Implemented a smart contract enabling freelancers to submit proposals 
- Created complete ProposalContract with submit/get/remove proposal functions, input validation, admin controls, and cross-contract FreelancerRegistry integration. Added comprehensive test suite with 9 passing tests covering all functionality and edge cases.
```bash
running 9 tests
test test::test_initialize_contract ... ok
test test::test_get_proposals_for_nonexistent_job ... ok
test test::test_submit_proposal_invalid_input ... ok
test test::test_initialize_already_initialized ... ok
test test::test_submit_proposal_success ... ok
test test::test_get_individual_proposal ... ok
test test::test_remove_proposal ... ok
test …
```
> feat: added proposal contract

- src/components/client-dashboard/DashboardActiveJobs.tsx
- Closes #255
Implements the **Active Jobs List** view for the Client Dashboard based on the Figma design: **Client Dashboard – Active Jobs**.
This view displays a list of ongoing job posts or contracts, each represented as a job card with metadata such as status, title, and relevant action buttons. It reflects real-time activity in the client’s dashboard and enhances the user experience by surfacing active engagements clearly.
- Created reusable component: `DashboardActiveJobs.tsx`
- Rendered `DashboardActiveJobs` conditionally inside `/dashboard/page.tsx`
- Implemented job card layout with:
- Status badge
- Title and brief details
- Action buttons (e.g., View, Edit)
- UI strictly matches spacing, colors, and typography from Figma
- Responsive layout for mobile and desktop screens
> feat: add DashboardActiveJobs component with job listing and actions

- contracts-offerhub/Cargo.lock
- contracts-offerhub/contracts/publication-contract/Cargo.toml
- contracts-offerhub/contracts/publication-contract/src/contract.rs
- contracts-offerhub/contracts/publication-contract/src/error.rs
- contracts-offerhub/contracts/publication-contract/src/event.rs
- contracts-offerhub/contracts/publication-contract/src/lib.rs
- contracts-offerhub/contracts/publication-contract/src/storage.rs
- contracts-offerhub/contracts/publication-contract/src/test.rs
- contracts-offerhub/contracts/publication-contract/test_snapshots/test/test_multiple_users_have_separate_counters.1.json
- contracts-offerhub/contracts/publication-contract/test_snapshots/test/test_publish_fails_on_invalid_type.1.json
- contracts-offerhub/contracts/publication-contract/test_snapshots/test/test_publish_fails_on_negative_amount.1.json
- contracts-offerhub/contracts/publication-contract/test_snapshots/test/test_publish_fails_on_short_title.1.json
- contracts-offerhub/contracts/publication-contract/test_snapshots/test/test_publish_project_and_user_counter.1.json
- contracts-offerhub/contracts/publication-contract/test_snapshots/test/test_publish_service_success.1.json
- Closes #246
This pull request introduces the complete `publication-contract`, a Soroban smart contract designed to act as a secure, on-chain registry for all service and project postings.
The primary goal is to enforce authenticated publishing from users, prevent spam, and create a verifiable, traceable record for every public offering on the platform before it is stored in an off-chain database like Supabase. The contract manages unique, user-specific publication IDs to track each user's posts individually.
- **`Contract.rs`**: Implemented the core `publish` function, which handles user authentication, input validation, storage, and event emission. A `get_publication` helper function was also added for easy on-chain verification.
- **`storage.rs`**: Defined the `PublicationData` struct …
> feat: publication contract

- backend/src/controllers/project.controller.ts
- backend/src/index.ts
- backend/src/routes/project.routes.ts
- backend/src/services/project.service.ts
- backend/src/types/project.type.ts
- Closes [236](https://github.com/OFFER-HUB/offer-hub/issues/236)
This PR implements the **Projects Module** for managing freelance job opportunities on the platform. Clients can create projects that freelancers will later apply to. The module includes:
- `controllers/project.controller.ts`
- `services/project.service.ts`
- `routes/project.routes.ts`
Each project includes the following fields: `title`, `description`, `budget`, `category`, and is associated with a `client_id`. Status transitions are tracked throughout the project lifecycle.
---
- **Description**: Allows clients to create a new project.
- **Required Fields**: `client_id`, `title`, `description`, `category`, `budget`
- **Response**: `201 Created` with the new project ID and metadata.
---
- **Description**: Lists all …
> Feat: create projects module

- contracts-offerhub/contracts/dispute-contract/README.md
- contracts-offerhub/contracts/dispute-contract/src/contract.rs
- contracts-offerhub/contracts/dispute-contract/src/lib.rs
- contracts-offerhub/contracts/dispute-contract/src/test.rs
- contracts-offerhub/contracts/dispute-contract/test_snapshots/test/test_resolve_dispute.1.json
- contracts-offerhub/contracts/dispute-contract/test_snapshots/test/test_resolve_dispute_already_resolved.1.json
- Closes #[issue-number] 
- Enhanced the dispute contract implementation with improved resolution mechanisms
- Added comprehensive test coverage for dispute resolution scenarios
- Updated contract logic to handle edge cases and error conditions more robustly
- Included detailed documentation for contract usage and setup
- **contract.rs**: Implemented enhanced dispute resolution logic and error handling
- **lib.rs**: Updated exports and core functionality interfaces  
- **test.rs**: Added new test cases covering dispute resolution scenarios and edge cases
- **test_snapshots/**: Updated snapshots to reflect new expected outputs after contract changes
- **README.md**: Added comprehensive documentation including setup instructions, usage examples, and API reference
> feat: Enhance Dispute Contract with Improved Resolution Logic

- backend/IMPLEMENTATION_SUMMARY.md
- backend/docs/ERROR_HANDLING_AND_VALIDATION.md
- backend/jest.config.js
- backend/package-lock.json
- backend/package.json
- backend/src/__tests__/setup.ts
- backend/src/controllers/contract.controller.ts
- backend/src/controllers/user.controller.ts
- backend/src/index.ts
- backend/src/middlewares/__tests__/errorHandler.test.ts
- backend/src/middlewares/errorHandler.middleware.ts
- backend/src/types/errors.types.ts
- backend/src/utils/AppError.ts
- backend/src/utils/__tests__/validation.test.ts
- backend/src/utils/validation.ts
> feat: standarize error

- src/app/find-workers/page.tsx
- src/data/generic-mock-data.ts
- src/hooks/useInitializeContract.ts
- src/hooks/useReleaseFunds.ts
- src/hooks/useResolveDispute.ts
- src/hooks/useStartDispute.ts
- src/hooks/useUpdateEscrow.ts
Clean imports
- Closes #427 
-
-
-
> feat: clean-imports

- src/components/auth/login-validation.tsx
- src/components/auth/validation-error.tsx
- src/hooks/use-auth-validation.ts
- src/types/auth-validation.types.ts
- src/utils/rate-limiting.ts
- src/utils/validation-rules.ts
- Closes #445 
This PR implements a comprehensive, production-ready login validation and error handling system. It enhances both user experience and security by providing robust client-side and server-side validation, real-time feedback, accessible error messaging, and rate limiting for failed login attempts.
- Added centralized validation rules for email and password strength
- Implemented a custom `useAuthValidation` hook for managing validation state and logic
- Created a reusable, accessible `ValidationError` component for error display
- Built a `LoginValidation` component with real-time validation feedback and loading states
- Integrated exponential backoff rate limiting for failed login attempts
- Improved error categorization and user feedback with actionable messages
- Ensured …
> Enhanced login validation

- backend/src/routes/service.routes.ts
- Closes #596 
- docs: add comprehensive API documentation for service routes
> docs: add comprehensive API documentation for service routes

- backend/.env.example
…tructure
- Closes #593
-This PR enhances the backend/.env.example file by adding clear and descriptive comments for all environment variables.
The goal is to make it easier for new developers to configure their environments correctly and securely.
-➕ Added section headers with separators for better organization.
-📝 Wrote descriptive comments above each environment variable.
-💡 Included usage tips, example values, and security notes (e.g., generating JWT secrets, Supabase URL format).
-🎯 Followed the clean and organized structure requested in the issue.
> docs: Add comments to environment variables in .env.example

- backend/supabase/migrations/20250717002200_12_create_workflow_tables.sql
- Closes #600
- Added SQL comments above each column definition in the workflow_stages table
-Each comment explains the purpose, constraints, and default values for the respective field.
-Comments are clear, concise, and follow SQL standards for documentation.
- Improved developer understanding of the dispute workflow schema by documenting all columns in workflow_stages with SQL comments.
> Fix: Implemented changes for issue #600

- backend/src/controllers/service.controller.ts
> docs: add JSDoc comments to getAllServicesHandler function

- services/freelance-matching/.env.example
- services/freelance-matching/bun.lock
- services/freelance-matching/src/ai/__tests__/low-cost-model.service.spec.ts
- services/freelance-matching/src/ai/__tests__/prefilter-benchmark.spec.ts
- services/freelance-matching/src/ai/ai.module.ts
- services/freelance-matching/src/ai/high-quality/__tests__/high-quality-model.service.spec.ts
- services/freelance-matching/src/ai/high-quality/high-quality-model.service.ts
- services/freelance-matching/src/ai/low-cost-model.service.ts
- services/freelance-matching/src/app.controller.ts
- services/freelance-matching/src/app.module.ts
- services/freelance-matching/src/match/__tests__/match.integration.spec.ts
- services/freelance-matching/src/match/match.controller.ts
- services/freelance-matching/src/match/match.module.ts
- services/freelance-matching/src/match/match.service.ts
- services/freelance-matching/src/queue/processors/embeddings.processor.ts
- services/freelance-matching/src/queue/queue.module.ts
- services/freelance-matching/src/queue/queue.service.ts
- Closes #531 
This PR implements prompt chaining with LangChain for the high-quality OpenAI model integration. This enhancement enables sophisticated reasoning capabilities for the refinement process in our freelance matching service.
- Created `HighQualityModelService` with LangChain integration for prompt chaining
- Implemented `executePromptChain` method that handles prompt templates and execution
- Added token limit checks to prevent exceeding model context windows
- Integrated performance tracking for monitoring latency
- Updated AI module to include the high-quality model service
- Added OPENAI_API_KEY validation in app configuration
- Uses LangChain's `RunnableSequence` for creating prompt chains
- Implements ChatPromptTemplate with system and user message templates
- Configures …
> feat: implement high quality model prompt chaining

- .npmrc
- src/components/common/primary-button.tsx
- src/components/common/secondary-button.tsx
- src/components/messagesComp/message-input.tsx
- src/components/ui/ResetPasswordPage.tsx
- src/components/ui/button.tsx
● 📝 Pull Request Title
Add loading states to button components and fix build configuration
🛠️ Issue
- Closes #648 
📚 Description
This PR implements loading states for all button components to improve user experience
during async operations and fixes build configuration issues that were preventing
successful compilation.
✅ Changes applied
🔄 Button Components with Loading States
- Enhanced src/components/ui/button.tsx:
- Added isLoading prop to ButtonProps interface
- Implemented loading spinner using consistent Loader2 from lucide-react
- Button automatically disables during loading state
- Loading spinner replaces button content when loading
- Created src/components/common/primary-button.tsx:
- New component wrapping base Button with variant="default"
- Inherits all loading functionality …
> closes issues: #648
